apiVersion: v1 #ConfigMap Definition to configure Prometheus 
kind: ConfigMap #Defines a ConfigMap resource in Kubernetes
metadata:
  name: prometheus-config # Name of the ConfigMap
  namespace: monitoring # The ConfigMap will be created inside the monitoring namespace
data:
  prometheus.yml: | # Everything after this is the real Prometheus configuration file   
    global: 
      scrape_interval: 15s

    rule_files: 
      - /etc/prometheus/rules/*.yml

    alerting: 
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager.monitoring.svc.cluster.local:9093']

    scrape_configs: 
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape your Flask app in sre-app namespace
      - job_name: 'sre-flask-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['sre-flask-app.sre-app.svc.cluster.local:5001']
